version: "3.7"

networks:
  unique-network:
    driver: bridge
    name: ${DOCKER_NETWORK:-unique-network}
    attachable: true

services:
  unique.marketplace:
    container_name: ${DOCKER_NAME:-unique.marketplace.latest}
    image: ${DOCKER_IMAGE:-unique.marketplace:latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV
    init: true
    tty: true
    stdin_open: true    
    ports:
      - 127.0.0.1:${DOCKER_PORT:-3000}:80
    networks:
      - ${DOCKER_NETWORK:-unique-network}
    logging:
      options:
        max-size: 10M
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: ${DOCKER_CPUS_LIMIT:-0.5}
          memory: ${DOCKER_MEMORY_LIMIT:-1024M}
    restart: always